# Weights and pathes
sketch_weights: ./weights/10_model.pth
sg_weight_path: ./weights/stylegan2-ffhq-256x256.pkl
mapper_pretrained_weights: ./weights/mapper_weights.pth
checkpoint_folder: checkpoints
output_folder: output

# Training
continue_training: True
num_epochs: 100
batch_size: 8
random_seed: 123
train_dataset_size: 5000
valid_dataset_size: 100
#start_learning_rate: 0.002  # LR для первой стадии обучения
start_learning_rate: 0.0015
image_size: 256


